import type { JobPosting } from "@/types/jobs";

export const MOCK_JOB_POSTINGS: JobPosting[] = [
  {
    id: "mock-1",
    title: "Junior Data Scientist",
    company: "Northstar Health",
    location: "Boston, MA",
    url: "https://example.com/jobs/junior-data-scientist",
    descriptionSnippet:
      "Support experimentation, SQL analysis, Python modeling, and Tableau dashboards for patient analytics.",
    salaryMin: 85000,
    salaryMax: 105000,
    salaryAverage: 95000,
    postedAt: "2026-04-21T09:00:00Z",
    remoteClassification: "Hybrid",
    skills: ["Python", "SQL", "Machine Learning", "Tableau", "Statistics"],
    contractType: "permanent",
    contractTime: "full_time",
    source: "mock",
  },
  {
    id: "mock-2",
    title: "Machine Learning Engineer",
    company: "Atlas Robotics",
    location: "Pittsburgh, PA",
    url: "https://example.com/jobs/machine-learning-engineer",
    descriptionSnippet:
      "Build PyTorch models, production APIs, Docker images, and AWS pipelines for perception systems.",
    salaryMin: 120000,
    salaryMax: 150000,
    salaryAverage: 135000,
    postedAt: "2026-04-22T13:30:00Z",
    remoteClassification: "On-site",
    skills: ["Python", "PyTorch", "AWS", "Docker", "APIs", "Computer Vision"],
    contractType: "permanent",
    contractTime: "full_time",
    source: "mock",
  },
  {
    id: "mock-3",
    title: "Software Engineer, Data Platform",
    company: "BlueCurrent",
    location: "Austin, TX",
    url: "https://example.com/jobs/software-engineer-data-platform",
    descriptionSnippet:
      "Create TypeScript services, Spark pipelines, Kubernetes deployments, and event-driven data tooling.",
    salaryMin: 112000,
    salaryMax: 142000,
    salaryAverage: 127000,
    postedAt: "2026-04-20T16:45:00Z",
    remoteClassification: "Remote",
    skills: ["TypeScript", "Spark", "Kubernetes", "Docker", "APIs", "AWS"],
    contractType: "permanent",
    contractTime: "full_time",
    source: "mock",
  },
  {
    id: "mock-4",
    title: "Data Analyst",
    company: "Civic Insights",
    location: "Washington, DC",
    url: "https://example.com/jobs/data-analyst",
    descriptionSnippet:
      "Deliver Excel, SQL, Tableau, and Power BI analysis for workforce and public sector reporting.",
    salaryMin: 72000,
    salaryMax: 92000,
    salaryAverage: 82000,
    postedAt: "2026-04-19T11:15:00Z",
    remoteClassification: "Hybrid",
    skills: ["SQL", "Excel", "Tableau", "Power BI", "Data Visualization"],
    contractType: "permanent",
    contractTime: "full_time",
    source: "mock",
  },
  {
    id: "mock-5",
    title: "Analytics Engineer",
    company: "Launchpad Commerce",
    location: "Chicago, IL",
    url: "https://example.com/jobs/analytics-engineer",
    descriptionSnippet:
      "Model business metrics in SQL, automate ETL, and partner with stakeholders on experimentation.",
    salaryMin: 98000,
    salaryMax: 126000,
    salaryAverage: 112000,
    postedAt: "2026-04-22T08:10:00Z",
    remoteClassification: "Remote",
    skills: ["SQL", "ETL", "Data Analysis", "A/B Testing", "Python"],
    contractType: "permanent",
    contractTime: "full_time",
    source: "mock",
  },
  {
    id: "mock-6",
    title: "AI Engineer",
    company: "Orchid Labs",
    location: "San Francisco, CA",
    url: "https://example.com/jobs/ai-engineer",
    descriptionSnippet:
      "Prototype LLM applications, retrieval workflows, API integrations, and evaluation pipelines on Azure.",
    salaryMin: 135000,
    salaryMax: 170000,
    salaryAverage: 152500,
    postedAt: "2026-04-23T07:40:00Z",
    remoteClassification: "Remote",
    skills: ["Python", "LLMs", "APIs", "Azure", "NLP", "Machine Learning"],
    contractType: "permanent",
    contractTime: "full_time",
    source: "mock",
  },
  {
    id: "mock-7",
    title: "Business Intelligence Analyst",
    company: "Harbor Retail",
    location: "Seattle, WA",
    url: "https://example.com/jobs/bi-analyst",
    descriptionSnippet:
      "Own dashboarding, Power BI models, SQL reporting, and executive business reviews for category growth.",
    salaryMin: 78000,
    salaryMax: 98000,
    salaryAverage: 88000,
    postedAt: "2026-04-18T18:05:00Z",
    remoteClassification: "Hybrid",
    skills: ["Power BI", "SQL", "Excel", "Data Visualization"],
    contractType: "permanent",
    contractTime: "full_time",
    source: "mock",
  },
  {
    id: "mock-8",
    title: "Junior Software Engineer",
    company: "Nebula Systems",
    location: "Raleigh, NC",
    url: "https://example.com/jobs/junior-software-engineer",
    descriptionSnippet:
      "Ship React and Next.js features, integrate APIs, write tests, and deploy cloud workloads with Docker.",
    salaryMin: 90000,
    salaryMax: 115000,
    salaryAverage: 102500,
    postedAt: "2026-04-23T10:20:00Z",
    remoteClassification: "Remote",
    skills: ["React", "Next.js", "TypeScript", "APIs", "Docker", "Git"],
    contractType: "permanent",
    contractTime: "full_time",
    source: "mock",
  },
  {
    id: "mock-9",
    title: "Machine Learning Research Engineer",
    company: "SignalWorks",
    location: "New York, NY",
    url: "https://example.com/jobs/ml-research-engineer",
    descriptionSnippet:
      "Train deep learning systems with PyTorch, experiment tracking, and distributed compute on GCP.",
    salaryMin: 140000,
    salaryMax: 176000,
    salaryAverage: 158000,
    postedAt: "2026-04-17T14:25:00Z",
    remoteClassification: "On-site",
    skills: ["PyTorch", "Deep Learning", "GCP", "Machine Learning", "Python"],
    contractType: "permanent",
    contractTime: "full_time",
    source: "mock",
  },
  {
    id: "mock-10",
    title: "Product Data Scientist",
    company: "ArcFin",
    location: "Charlotte, NC",
    url: "https://example.com/jobs/product-data-scientist",
    descriptionSnippet:
      "Run causal analysis, build churn models, and communicate findings with experimentation and SQL rigor.",
    salaryMin: 110000,
    salaryMax: 138000,
    salaryAverage: 124000,
    postedAt: "2026-04-21T20:00:00Z",
    remoteClassification: "Hybrid",
    skills: ["Python", "SQL", "Statistics", "Machine Learning", "A/B Testing"],
    contractType: "permanent",
    contractTime: "full_time",
    source: "mock",
  },
  {
    id: "mock-11",
    title: "Data Engineer",
    company: "ClearRoute Energy",
    location: "Denver, CO",
    url: "https://example.com/jobs/data-engineer",
    descriptionSnippet:
      "Build ETL jobs, Airflow orchestration, Spark transforms, and cloud storage pipelines on AWS.",
    salaryMin: 118000,
    salaryMax: 148000,
    salaryAverage: 133000,
    postedAt: "2026-04-23T03:15:00Z",
    remoteClassification: "Remote",
    skills: ["Python", "SQL", "Spark", "Airflow", "ETL", "AWS"],
    contractType: "permanent",
    contractTime: "full_time",
    source: "mock",
  },
  {
    id: "mock-12",
    title: "Data Analytics Intern",
    company: "Brightline Logistics",
    location: "Atlanta, GA",
    url: "https://example.com/jobs/data-analytics-intern",
    descriptionSnippet:
      "Support KPI dashboards, Excel analysis, SQL data pulls, and storytelling for operations leaders.",
    salaryMin: null,
    salaryMax: null,
    salaryAverage: null,
    postedAt: "2026-04-16T09:50:00Z",
    remoteClassification: "On-site",
    skills: ["Excel", "SQL", "Data Analysis", "Data Visualization"],
    contractType: "contract",
    contractTime: "full_time",
    source: "mock",
  },
];
